unique_ids:
  assets:
    standard-page.html: PCD7CVWBNUNLMZPPSOKVAU7ZVBXMAVRC
    theme.css: XCID2I3MKM6VS2VUFVYZQSR7QX44D4WV
  forms:
    Form1: 4LA7FSHEUEFEXOPD2UZKOCGUCQXIMBU3
  modules: {}
  scripts: {}
  server_modules: {}
